version: '3.1'

services:
  server: 
    container_name: server-intro
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on: 
      - db
      - ftp
    volumes: 
      - ftp:/app/ftpdata
  db:
    image: postgres:15
    container_name: intro_db
    restart: always
    env_file:
      - ../dev.env
    ports:
      - 5433:5432
    volumes: 
      - db:/var/lib/postgresql/data/
  ftp:
    image: fauria/vsftpd
    container_name: vsftpd
    restart: always
    env_file: 
      - ../dev.env
    ports:
      - '2022:22/tcp'
      - '21:21/tcp'
      - '21100-21110:21100-21110/tcp'
    volumes:
      - 'ftp:/home/vsftpd:z'
volumes:
  db:
  ftp: