version: '3.1'

services: 
  ftp:
    image: fauria/vsftpd
    container_name: vsftpd
    env_file: 
      - ../dev.env
    ports:
      - '2022:22/tcp'
      - '21:21/tcp'
      - '21100-21110:21100-21110/tcp'
    volumes:
      - '/home/ikbkr/ftpdata:/home/vsftpd'
volumes:
  ftp: